### PR TITLE
pay any asset

### PR DESCRIPTION
**Pull request by vakar8888**
Added some code which allows to pay out any asset.

### CODE REVIEW

**Comment by tonyofbyteball** [comment]
The functionality is useful, but some code changes are necessary:
* why require() network?
* meaning of Org suffix is unclear
* give descriptive names to variables, no p, no q, wordOne is command, the rest are params
* would be nice to check that the requested asset exists before attempting to send a payment

**Comment by vakar8888** [comment]
>    why require() network?
removed

> meaning of Org suffix is unclear
removed

>    give descriptive names to variables, no p, no q, wordOne is command, the rest are params
renamed

>    would be nice to check that the requested asset exists before attempting to send a payment
added

**Comment by tonyofbyteball** [comment]
Thanks that's better but it seems this check was lost:
```
			if (!conf.payout_address)
				return device.sendMessageToDevice(from_address, 'text', "payout address not defined");
```
Also please use strict comparison (===, not ==) whenever relevant.

**Comment by vakar8888** [comment]
- check for payout address added
- comparisons changed to strict comparison

**Pull request merged**
